<a href="https://colab.research.google.com/github/abhi2666/Deep-Learning/blob/main/ANN_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [4]:
#checking version of tensorflow
tf.__version__

'2.8.0'

In [5]:
dataset = pd.read_csv("Churn_Modelling.csv")
#x -> matrix of features
#y -> labels
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


In [8]:
#Encoding the features
# 1--> Encoding Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [9]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
# 2--> Encoding Countries
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
# Final Encoded matrix of features
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
#Splitting of the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [13]:
print(y_test)

[0 0 0 ... 1 1 1]


In [14]:
#Feature Scaling
#In Deep Learning, feature scaling is a must and to be whole matrix of feautres
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
#BUILDING THE ANN

#initialzing 

ann = tf.keras.models.Sequential()
#creating first layer(including hidden layer)
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) #unit->no. of neuron that you want #relu-->rectified activation function
#adding second layer
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

#adding output layer
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) #unit - 1 because output will be only 1 or 0

In [17]:
#TRAINING THE ANN

#compiling the ANN
ann.compile(optimizer = 'adam', loss=  'binary_crossentropy', metrics = ['accuracy'])


In [28]:
ann.fit(x_train, y_train, batch_size = 32, epochs=100) #epochs - no. of times the value of w1...wm gets modified to lower the cost function


Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3295 - accuracy: 0.8651
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3293 - accuracy: 0.8655
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.8650
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3292 - accuracy: 0.8660
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8661
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.8658
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3289 - accuracy: 0.8649
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3292 - accuracy: 0.8649
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3292 - accuracy: 0.8649
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3289 - accura

In [29]:
#testing with custom inputs
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
# if it is more than 50% then return true else false

[[False]]


In [30]:
#determining accuracy
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [31]:
print(cm)

[[1533   74]
 [ 205  188]]


In [32]:
print(acc)

0.8605
